# Generated by Django 2.0 on 2019-06-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='Product_class',
            new_name='Product_Class',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='Product_color',
            new_name='Product_Color',
        ),
        migrations.RenameField(
            model_name='productdata',
            old_name='Product_cost',
            new_name='Product_Cost',
        ),
    ]
